spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy
    url: jdbc:mysql://db:3306/justudy?serverTimezone=UTC&characterEncoding=UTF-8
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # ddl-auto : create -> Entity에 맞게 자동으로 테이블 및 필드 생성
  # show-sql : true -> 해당하는 query를 보여줌 (JPA N + 1 문제 확인용)
  jpa:
    database: mysql   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  ## page 인덱스를 1부터 시작하게 만듬
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    org.hibernate.sql: debug

vue:
  loginUrl: "localhost:8081/login"


